#!/bin/bash
# Cluely Xcode Project Setup Instructions
# This script documents the required Xcode configuration

echo "======================================"
echo "Cluely visionOS Project Setup Guide"
echo "======================================"
echo ""
echo "STEP 1: Create New Xcode Project"
echo "  1. Open Xcode"
echo "  2. File → New → Project"
echo "  3. Select: visionOS → App"
echo "  4. Product Name: Cluely"
echo "  5. Organization Identifier: com.example"
echo "  6. Interface: SwiftUI"
echo "  7. Language: Swift"
echo "  8. Save to: $(pwd)"
echo ""
echo "STEP 2: Remove Default Files"
echo "  - Delete ContentView.swift"
echo "  - Delete any auto-generated preview files"
echo ""
echo "STEP 3: Add Required Frameworks"
echo "  1. Click 'Cluely' project (blue icon at top)"
echo "  2. Select 'Cluely' under TARGETS"
echo "  3. Go to 'Frameworks, Libraries, and Embedded Content'"
echo "  4. Click '+' button and add:"
echo "     ✓ AVFoundation.framework"
echo "     ✓ Vision.framework"
echo "     ✓ ReplayKit.framework"
echo "     ✓ Accelerate.framework"
echo ""
echo "STEP 4: Add All Source Files"
echo "  1. Right-click 'Cluely' folder in project navigator"
echo "  2. Select 'Add Files to Cluely...'"
echo "  3. Navigate to: CluelyApp/"
echo "  4. Select these folders/files:"
echo "     ✓ Input/ (VAD.swift)"
echo "     ✓ Session/ (6 files)"
echo "     ✓ Views/ (9 files)"
echo "     ✓ App.swift"
echo "     ✓ Config.swift"
echo "     ✓ Resources/Info.plist"
echo "  5. Check 'Copy items if needed'"
echo "  6. Check 'Create groups'"
echo "  7. Click 'Add'"
echo ""
echo "STEP 5: Configure Info.plist"
echo "  1. Select Info.plist in project navigator"
echo "  2. Verify these keys exist:"
echo "     ✓ NSMicrophoneUsageDescription"
echo "     ✓ WSURL = ws://localhost:8080/ws"
echo ""
echo "STEP 6: Set Deployment Target"
echo "  1. Select 'Cluely' target"
echo "  2. General tab"
echo "  3. Set 'Minimum Deployments' to: visionOS 1.0"
echo ""
echo "STEP 7: Select Simulator"
echo "  1. At top of Xcode, click device dropdown"
echo "  2. Select: 'Apple Vision Pro' (Simulator)"
echo ""
echo "STEP 8: Build & Run"
echo "  1. Press ▶ button or Cmd+R"
echo "  2. Wait for build to complete"
echo "  3. App should launch in simulator!"
echo ""
echo "======================================"
echo "Required Frameworks Summary:"
echo "======================================"
echo "✓ SwiftUI (included by default)"
echo "✓ AVFoundation - Audio capture"
echo "✓ Vision - OCR text recognition"
echo "✓ ReplayKit - Screen capture"
echo "✓ Accelerate - Audio processing (VAD)"
echo ""
echo "Files to Add (18 total):"
echo "======================================"
echo "Core:"
echo "  - App.swift"
echo "  - Config.swift"
echo ""
echo "Input/ (1 file):"
echo "  - VAD.swift"
echo ""
echo "Session/ (6 files):"
echo "  - AudioEngine.swift"
echo "  - CoachRuntime.swift"
echo "  - FrameSource.swift"
echo "  - Models.swift"
echo "  - SessionController.swift"
echo "  - WSClient.swift"
echo ""
echo "Views/ (9 files):"
echo "  - CoachChip.swift"
echo "  - CoachView.swift"
echo "  - ContextCard.swift"
echo "  - FramePreviewCard.swift"
echo "  - ListeningIndicator.swift"
echo "  - OrnamentControls.swift"
echo "  - RootWindow.swift"
echo "  - SuggestionPanel.swift"
echo "  - WarningBadge.swift"
echo ""
echo "Resources/ (1 file):"
echo "  - Info.plist"
echo ""
echo "======================================"
echo "Need Help? Check INSTRUCTIONS.md"
echo "======================================"
